# Book settings
title                       : FLUXNET Open-Source Code Committee  # The title of the book. Will be placed in the left navbar.
author                      : FLUXNET Code Committee # The author of the book
copyright                   : '2023'
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

execute:
  execute_notebooks: 'off'
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true
  use_edit_page_button      : true
  use_issues_button         : true


repository:
  url                       : https://github.com/fluxnet-open-source/resources-guide  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links

parse:
  myst_enable_extensions:
    - attrs_inline

sphinx:
  config:
    exclude_patterns:
      - README.md
